spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_order?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}

# MyBatis Mapper 扫描
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

eureka:
  instance:
    # 以IP注册到注册中心
    preferIpAddress: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    # 服务的一些元数据信息
    metadata-map:
      VERSION: 0.11.0
  client:
    serviceUrl:
      # 注册中心地址，多个用逗号隔开
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://dev.hzero.org:18000/eureka}
    registryFetchIntervalSeconds: 10
    disable-delta: true

# 日志配置
logging:
  level:
    org.hzero: ${LOG_LEVEL:debug}
    org.apache.ibatis: ${LOG_LEVEL:debug}
    io.choerodon: ${LOG_LEVEL:debug}
hzero:
  lov:
    value:
      enabled: true
  import:
          init-table: true
  scheduler:
          auto-register: false

